/*
Standard Model: FTC Team 9372
Current Autonomous Code
(c) January, 2015
*/
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     sonarSensor,    sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     stomper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    tubeHolderServo,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    boxServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    tubeGrabberServo,     tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    backwardsModeServo,   tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
    
	waitForStart();
    
    //These are the values for what the ultrasonic sensor should see depending on the position of the center goal.
    
	//position3: 106 cm
	//position2: 255 cm
	//position1: 125-130 cm
    
    //drive backwards 500 ticks to send position of center goal
	nMotorEncoder[rightBack] = 0;
	motor[rightBack] = motor[rightFront] = motor[leftBack] = motor[leftFront] = -30;
	while(nMotorEncoder[rightBack] > -500);
	motor[rightBack] = motor[rightFront] = motor[leftBack] = motor[leftFront] = 0;
	nMotorEncoder[rightBack] = 0;
    
    //set variables of center goal distances
	int pos1cm = 135; //furthest
	int pos2cm = 255; //middle
	int pos3cm = 80; //closest
    
    
    //variable to hold drive power
	int drivePower = 40;
    
    //record distance from center goal
	int cmFromCenter = SensorValue(sonarSensor);
    
    //variable to hold the position of the center goal
	int pos = 0;
    
    //get the difference between the distance from the center goal and expected distances between the robot and each position
	int p1Dist = abs(pos1cm-cmFromCenter);
	int p2Dist = abs(pos2cm-cmFromCenter);
	int p3Dist = abs(pos3cm-cmFromCenter);
    
    
    //If the distance from the center goal matches position 1 better than it matches 2 or 3, set the value of 'pos' to 1
	if(p1Dist < p2Dist && p1Dist < p3Dist) {
		pos = 1;
	}
    
    //If the distance from the center goal matches position 2 better than it matches 1 or 3, set the value of 'pos' to 2
	if(p2Dist < p1Dist && p2Dist < p3Dist) {
		pos = 2;
	}
    
    //If the distance from the center goal matches position 3 better than it matches 1 or 2, set the value of 'pos' to 3
	if(p3Dist < p1Dist && p3Dist < p2Dist) {
		pos = 3;
	}
    
    
    //position 3 code
	if(pos==3) {
        //close box servo
		servo[boxServo] = 192;
        
		//raise stomper a little
		motor[stomper] = 10;
		wait1Msec(1000);
		motor[stomper] = 0;
        
		//stomper servo
		servo[tubeHolderServo] = 83;
        
        
		//go forward
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -1900) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = -drivePower;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//lifting lift up to center
		nMotorEncoder[lift] = 0;
		while(nMotorEncoder[lift] < 11000)
			motor[lift] = 100;
		motor[lift] = 0;
        
		//moving forward again
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -350) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = -drivePower;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		wait1Msec(1000); //give the lift a second to stop swinging so hard
        
		//release balls into center goal
		servo[boxServo] = 0;
		wait1Msec(1000);
        
        
		//move back
        
		nMotorEncoder[rightBack] = 0;
		nMotorEncoder[leftBack] = 0;
		while(SensorValue(sonarSensor) < 19) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = drivePower/4;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//lower lift
		nMotorEncoder[lift] = 0;
		while(nMotorEncoder[lift] > -10500)
			motor[lift] = -10;
		motor[lift] = 0;
        
        
		//close the box servo
		servo[boxServo] = 192;
        
        
	}
	else if(pos==2) {
		//code for position 2
        
		servo[boxServo] = 192;
        
		//raise stomper a little
		motor[stomper] = 10;
		wait1Msec(1000);
		motor[stomper] = 0;
        
		//stomper servo
		servo[tubeHolderServo] = 83;
        
        
		//go forward
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -600) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = -drivePower;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//turn 90 degrees
        
		motor[rightBack] = motor[rightFront] = drivePower;
		motor[leftBack] =  motor[leftFront] =  -drivePower;
        
		nMotorEncoder[rightBack] = 0;
        
		while(nMotorEncoder[rightBack] < 500);
        
		motor[rightBack] = motor[rightFront] = 0;
		motor[leftBack] =  motor[leftFront] =  0;
        
		//go forwards
		motor[rightBack] = motor[leftFront] = -50;
		motor[rightFront] = motor[leftBack] = -50;
        
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -1900);
		nMotorEncoder[rightBack] = 0;
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//turn back
        
		motor[rightBack] = motor[rightFront] = -drivePower;
		motor[leftBack] =  motor[leftFront] =  drivePower;
        
		nMotorEncoder[rightBack] = 0;
        
		while(nMotorEncoder[rightBack] > -2400);
        
		motor[rightBack] = motor[rightFront] = 0;
		motor[leftBack] =  motor[leftFront] =  0;
        
        
		//lifting lift up to center
		nMotorEncoder[lift] = 0;
		while(nMotorEncoder[lift] < 11000)
			motor[lift] = 100;
		motor[lift] = 0;
        
		//moving forward again
		nMotorEncoder[rightBack] = 0;
		while(SensorValue(sonarSensor) > 15) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = -drivePower/4;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		wait1Msec(1000); //give the lift a second to stop swinging so hard
        
		//release balls into center goal
		servo[boxServo] = 0;
		wait1Msec(1000);
        
		//move back
        
		nMotorEncoder[rightBack] = 0;
		nMotorEncoder[leftBack] = 0;
		while(nMotorEncoder[rightBack] < 500 && nMotorEncoder[leftBack] < 500) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = drivePower/4;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//lower lift
		nMotorEncoder[lift] = 0;
		while(nMotorEncoder[lift] > -10500)
			motor[lift] = -10;
		motor[lift] = 0;
        
        
		//close the box servo
		servo[boxServo] = 192;
        
        
	}
    
	else if(pos==1) {
        
        //code for position 1
        
        //close box servo
		servo[boxServo] = 192;
        
		//raise stomper a little
		motor[stomper] = 10;
		wait1Msec(1000);
		motor[stomper] = 0;
        
		//stomper servo
		servo[tubeHolderServo] = 83;
        
        
		//go forward
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -600) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = -drivePower;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//turn 90 degrees
		motor[rightBack] = motor[rightFront] = drivePower;
		motor[leftBack] =  motor[leftFront] =  -drivePower;
        
		nMotorEncoder[rightBack] = 0;
        
		while(nMotorEncoder[rightBack] < 1000);
        
		motor[rightBack] = motor[rightFront] = 0;
		motor[leftBack] =  motor[leftFront] =  0;
        
		//go forwards
		motor[rightBack] = motor[leftFront] = -50;
		motor[rightFront] = motor[leftBack] = -50;
        
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -2500);
		nMotorEncoder[rightBack] = 0;
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//turn back
		motor[rightBack] = motor[rightFront] = -50;
		motor[leftBack] = motor[leftFront] = 50;
        
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -2000);
		nMotorEncoder[rightBack] = 0;
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//go forward
		motor[rightBack] = motor[rightFront] = -50;
		motor[leftBack] = motor[leftFront] = -50;
        
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -2900);
		nMotorEncoder[rightBack] = 0;
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//turn towards
		motor[rightBack] = motor[rightFront] = -50;
		motor[leftBack] = motor[leftFront] = 50;
        
		nMotorEncoder[rightBack] = 0;
		while(nMotorEncoder[rightBack] > -2200);
		nMotorEncoder[rightBack] = 0;
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
        
		//lifting lift up to center
		nMotorEncoder[lift] = 0;
		while(nMotorEncoder[lift] < 11000)
			motor[lift] = 100;
		motor[lift] = 0;
        
		//moving forward again
		nMotorEncoder[rightBack] = 0;
		while(SensorValue(sonarSensor) > 13) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = -drivePower/4;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		wait1Msec(1000); //give the lift a second to stop swinging so hard
        
		//release balls into center goal
		servo[boxServo] = 0;
		wait1Msec(1000);
        
		//move back
        
		nMotorEncoder[rightBack] = 0;
		nMotorEncoder[leftBack] = 0;
		while(nMotorEncoder[rightBack] < 500 && nMotorEncoder[leftBack] < 500) {
			motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = drivePower/4;
		}
		motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
        
		//lower lift
		nMotorEncoder[lift] = 0;
		while(nMotorEncoder[lift] > -10500)
			motor[lift] = -10;
		motor[lift] = 0;
        
        
		//close the box servo
		servo[boxServo] = 192;
        
        
	}
    
    //code to knock over the kickstand, this is the same for each position
    //(because the position of the kickstand is constant relative to that of the center goal)
    
    //close box servo
	servo[boxServo] = 255;
    
	//strafe right
	motor[rightBack] = motor[leftFront] = -50;
	motor[rightFront] = motor[leftBack] = 50;
    
	nMotorEncoder[rightBack] = 0;
	while(nMotorEncoder[rightBack] > -1600);
	nMotorEncoder[rightBack] = 0;
	motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
    
    
	//go forwards
    
	motor[rightBack] = motor[leftFront] = -50;
	motor[rightFront] = motor[leftBack] = -50;
    
	nMotorEncoder[rightBack] = 0;
	while(nMotorEncoder[rightBack] > -2300);
	nMotorEncoder[rightBack] = 0;
	motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
    
    
	//spin right to pull out kickstand
	motor[rightBack] = motor[leftFront] = 50;
	motor[rightFront] = motor[leftBack] = -50;
    
	nMotorEncoder[rightBack] = 0;
	while(nMotorEncoder[rightBack] > -1500);
	nMotorEncoder[rightBack] = 0;
	motor[rightBack] = motor[leftBack] = motor[rightFront] = motor[leftFront] = 0;
    
    
}
